timezone: Europe/Oslo
encoding: utf-8
exclude: ["vendor", "fendtek"]

defaults:
  -
    scope:
      path: .
      type: "pages"
    values:
      layout: default
      title: "Courses by arejo"
  -
    scope:
      path: "matforslag"
      type: "pages"
    values:
      layout: default
      title: "Matforslag"
